tpl_base/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('core.views',
    url(r'^$', 'index', name='index'),
    url(r'^page/(?P<page>.+)/$', 'page', name='page'),
    url(r'^unsubscribe/(?P<card_number>.*)/$', 'unsubscribe', name='unsubscribe'),
)

tpl_base/tplreminder/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('core.urls')),
    # url(r'^tplreminder/', include('tplreminder.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

tpl_base/core/models.py
from Crypto.Cipher import AES
from base64 import b64encode, b64decode
from django.conf import settings
from django.db import models
from core import utils


class LibraryAccount(models.Model):
    creation_time = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=255)
    card_number = models.CharField(max_length=30, db_index=True)
    pin = models.CharField(max_length=256)
    last_check = models.DateTimeField()

    def mark_as_checked(self):
        """
        Tells this account to remember that it was checked against the TPL site
        as of this instant.
        """
        self.last_check = utils.sane_now()
        self.save()

    def encrypt_pin(self):
        e = AES.new(settings.SECRET_KEY[:32])
        self.pin = b64encode(e.encrypt(self.pin.ljust(32)))

    def get_pin(self):
        e = AES.new(settings.SECRET_KEY[:32])
        pin = e.decrypt(b64decode(self.pin)).strip()
        return pin

tpl_base/core/forms.py
from django.forms import ModelForm, PasswordInput
from core.models import LibraryAccount


class LibraryAccountForm(ModelForm):
    class Meta:
        model = LibraryAccount
        fields = ('card_number', 'pin', 'email')
        widgets = {
            'pin' : PasswordInput(),
        }

    def clean(self):
        cleaned_data = super(LibraryAccountForm, self).clean()

        stripped_number = cleaned_data.get('card_number', '').replace(" ", "")    
        cleaned_data['card_number'] = stripped_number

        return cleaned_data

tpl_base/core/views.py
import datetime
import logging
logger = logging.getLogger(__name__)

from django.conf import settings
from django.http import Http404
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from core.forms import LibraryAccountForm

def index(request):
    bad_login = False

    if request.method == "POST":
        form = LibraryAccountForm(request.POST)
        if form.is_valid():
            new_account = form.save(commit=False)

            if settings.CONTEXT.TPLService.test_login(new_account):
                settings.CONTEXT.AccountService.register_new(new_account)
                logger.info('Registered new account %s' % new_account.card_number)
                return redirect(page, page="thanks")
            else:
                logger.info('Login failure @reg %s %s' %
                        (new_account.card_number, new_account.email))
                bad_login = True

    else:
        form = LibraryAccountForm()

    return render_to_response("index.html", {
            'form' : form,
            'bad_login' : bad_login,
        },
        context_instance=RequestContext(request)
    )

def page(request, page):
    try:
        return render_to_response(
                "{0}.html".format(page),
                context_instance=RequestContext(request)
        )
    except: 
        raise Http404

def unsubscribe(request, card_number):
    account = settings.CONTEXT.AccountService.get(card_number)
    if not account:
        raise Http404

    if request.method == "POST":
        settings.CONTEXT.AccountService.unsubscribe(account)
        logger.info('Unsubscribed: %s' % account.card_number)
        return redirect(page, page="unsubscribe-done")
    else:
        return render_to_response("unsubscribe.html", {
                'account' : account,
            },
            context_instance=RequestContext(request)
        )

tpl_base/core/templates/base.html
<html>
<head>
    <title>Toronto Public Library Overdue Book Reminder</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
</head>
<body>
    <h1>{% block heading %}Toronto Public Library Book Reminder{% endblock %}</h1>
    <div id="container">
        {% block content %}{% endblock %}
    </div>
</body>
</head>

tpl_base/core/templates/index.html
{% extends "base.html" %}
{% block content %}
    <p>
        We'll send you email 3 days before your books are due.   
    </p>
    <form method="POST" action=".">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <div align="center">
            <input type="submit" value="Sign up" />
        </div>
    </form>
    {% if bad_login %}
        <p>
        I'm afraid we couldn't log you in. Are you sure you gave us the
        right barcode # and PIN? (Your PIN is usually the last 4 numbers of
        your phone number.)
        </p>
    {% endif %}
    <div align="center">
    <ul class="questions">
        <li><a href="/page/what/">What is this?</a></li>
        <li>|</li>
        <li><a href="/page/safe/">Is it safe?</a></li>
        <li>|</li>
        <li><a href="http://mikedebo.ca">Who made this?</a></li>
    </ul>
    </div>
    <script>
        $(document).ready(function() {
            $("#id_card_number").focus();
        });
    </script>
{% endblock %}

tpl_base/core/templates/notification-email.html
<h2>This is your library loan reminder from tplreminder.</h2>
{% if overdue %}
    <h3>These books are <span style="color: red">OVERDUE</span><h3>
    <table cellpadding=3>
	<tr>
	    <th>Book</th>
	    <th>Due Date</th>
	    <th>Renewals Left</th>
	    <th>Link</th>
	</tr>
    {% for loan in overdue %}
	<tr>
	    <td>{{ loan.title }}</td>
	    <td>{{ loan.due_date }}</td>
	    <td>{{ loan.renewals_left }}</td>
	    <td><a href="{{ loan.link }}">Click</a></td>
	</tr>
    {% endfor %}
    </table>
{% endif %}
{% if coming_due %}
    <h3>These books are due in the next 3 days<h3>
    <table>
	<tr>
	    <th>Book</th>
	    <th>Due Date</th>
	    <th>Renewals Left</th>
	    <th>Link</th>
	</tr>
    {% for loan in coming_due %}
	<tr>
	    <td>{{ loan.title }}</td>
	    <td>{{ loan.due_date }}</td>
	    <td>{{ loan.renewals_left }}</td>
	    <td><a href="{{ loan.link }}">Click</a></td>
	</tr>
    {% endfor %}
    </table>
{% endif %}

tpl_base/core/templates/safe.html
{% extends "base.html" %}
{% block heading %}
Security
{% endblock %}
{% block content %}
<h2>Is this safe?</h2>
<p>
In short: use at your own risk.
</p> 
<p>
When you log in with your card number and PIN, we save your information in our
database. We encrypt your PIN before saving it. All communications between you
and us and between us and the TPL are done over HTTPS. We've taken the
most basic of precautions to keep your data safe.
</p>
<p>
The way that we figure out if your books are due is by "pretending" that we're
you. That is, our servers log into your account for you, take a peek at your
loans chart, and if they see anything that's coming due, they email you. That's
why we have to save your PIN.
</p>
<p>
If someone does hijack your info, we think they worst they can do is reserve a
bunch of books without you knowing it. The TPL charges $1 for every book that
you reserve but fail to pick up.
</p>
<p>
Just to make it clear: We take no responsibility for any theft or loss of
library card information as a result of using this site.
</p>
{% endblock %}

tpl_base/core/templates/thanks.html
{% extends "base.html" %}
{% block heading %}
You're done.
{% endblock %}
{% block content %}
<p>
    We'll remind you next time your books are coming due.
</p>
{% endblock %}

tpl_base/core/templates/unsubscribe-done.html
{% extends "base.html" %}
{% block heading %}You are unsubscribed.{% endblock %}
{% block content %}
<p>If you want to start receiving emails again, just go back to <a href="/">Sign up</a>.
</p>
{% endblock %}

tpl_base/core/templates/unsubscribe.html
{% extends "base.html" %}
{% block heading %}Unsubscribe?{% endblock %}
{% block content %}
{% if account %}
    <p>If you don't want to receive emails anymre about books coming due for card '{{ account.card_number }}', click the button below.</p>
    <form method="POST" action=".">
        {% csrf_token %}
        <input type="submit" value="Unsubscribe Me" />
    </form>
{% else %}
{% endif %}
{% endblock %}

tpl_base/core/templates/what.html
{% extends "base.html" %}
{% block heading %}
Questions
{% endblock %}
{% block content %}
<h2>What?</h2>
<p>
The <a href="http://www.torontopubliclibrary.ca/">Toronto Public Library</a> allows you to
renew books online, which is great. However, they only email you after your
books are <em>overdue</em>.</p> 

<p>They are apparently <a href="http://torontopubliclibrary.typepad.com/webteam/2012/02/improvements-to-holds-and-overdue-notification.html">working on it</a>, but you can use this to send you reminders until then. It will check your account once a day, and if your books are coming due in the next 3 days, it will email you a warning.
</p>

<h2>Why?</h2>

<p>It bothers me that TPL can't already do this.</p>
</p>

<p>
Note that I'm not blaming them for anything. I have no idea what
proprietary system they may be locked into using, but I've worked with
enough of those to know how painful the simplest changes can be.
</p>

<p>
Then again, maybe it was just a money grab. Even then, I don't blame them. I'd
rather the money come from voluntary contributions, though. So, if you find
this service useful, <a href="http://tplfoundation.ca/become_a_donor">consider
    donating to the TPL</a>. 
</p>

<h2>How?</h2>
<p>
For those of you who are technically inclined, <code>tplreminder</code> is a Python/Django
app, although the core fetching and parsing stuff is just pure Python. 
</p>

<p>
If you want to run this locally instead of using the public service (which
keeps your library card numbers and PINs in your own datasphere), you can find
the project <a href="https://github.com/MichaelDiBernardo/tplreminder">on Github</a>.
</p>
{% endblock %}